### PR TITLE
Deletable file paths, because my list is at 100+ long....

### PR DESCRIPTION
**Pull request by XScorpion2**
Related issue(s) (if any):

Changes:
Mouse over item in File Path Dropdown, hit delete, item is now deleted

### CODE REVIEW

**Comment by fauxpark** [comment]
Hmm, I think I would prefer something more intuitive and idiomatic, like a File -> Open Recent menu with a Clear button.

**Comment by XScorpion2** [comment]
This implementation is the same as Firefox's url bar when searching. Also there's no existing menus in qmk toolbox, so doing that would require a lot more code and ui changes.

**Comment by fauxpark** [comment]
> This implementation is the same as Firefox's url bar when searching.

Didn't know that was a thing. Still doesn't seem very obvious. Also, you've only changed this for the Windows Toolbox - we should really try to keep the two in sync.

> Also there's no existing menus in qmk toolbox, so doing that would require a lot more code and ui changes.

macOS always has a menu bar ;) Although yeah, there's nothing on it at present.

**Comment by XScorpion2** [comment]
I don't have a mac on hand, so someone else will need to do that side of things.
Though this does point out a reason to look into something more cross platform compatible for code & ui

**Pull request merged**
