### PR TITLE
Add GD32V bindings.

### PR DESCRIPTION
**Pull request by tzarc**
## Description

Add support for GD32V DFU.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Documentation

### CODE REVIEW

**Comment by tzarc** [comment]
Still needs adding to the first-load console output showing what devices are supported.

**Comment by tzarc** [comment]
Tested on both platforms.

**Comment by KarlK90** [comment]
GD32VF bootloader contains a bug and reports a page size of 2048 bytes. This is fixed by dfu-util 0.10. As a precaution the dfu-util version should be checked, otherwise this would result in a bricked keyboard.

**Comment by tzarc** [comment]
> GD32VF bootloader contains a bug and reports a page size of 2048 bytes. This is fixed by dfu-util 0.10+. As a precaution the dfu-util version should be checked, otherwise this would result in a bricked keyboard.

Both platforms are at 0.11 already.

**Comment by KarlK90** [comment]
Alright, if there is no way we can have a dfu-util version below that on these this check is unnecessary.

**Review by KarlK90 — APPROVED** [review]

**Pull request merged**
