### PR TITLE
Add support for Adafruit FeatherBLE 32u4

### PR DESCRIPTION
**Pull request by colemarkham**
Add support Adafruit Feather BLE 32u4, Issue #10

### CODE REVIEW

**Comment by colemarkham** [comment]
Realized that I only fixed it for OSX since it's in 2 different places so I added it to the Windows version as well.

**Comment by jackhumbert** [comment]
Awesome! Thanks :) We might need to change the names down the road to better represent what the compares are doing, but this will work for now!

**Comment by colemarkham** [comment]
Thanks, Jack. How would I go about making a build for Windows so I can get it to some of my customers?

**Comment by drashna** [comment]
Download Visual Studio Community, clone the repo, open QMK Toolbox\Windows\QMK Toolbox.sln, and build it. 

It should create a folder in "\windows\QMK Toolbox\bin\Release" that has the EXE.  Grab that.

At least, that's what works for me.

**Comment by jackhumbert** [comment]
@drashna is right on, but I need to make a new release anyway - lemme work on that today!

**Comment by drashna** [comment]
Awesome on both accounts. :)

**Pull request merged**
